Feature/ice creams and drinks
mateogaudi/recipes-and-cook-classes pull request #4
Opened 2020-12-18 00:48 UTC by mateogaudi

2020-12-28 23:27 UTC, thesvst requested changes

2020-12-28 23:27 UTC, thesvst commented on assets/scss/sections/_ice-creams-and-drinks.scss
> +    height:80vh;
Do wywalenia. Nie ogarniczamy wysokości tej sekcji. 
Wysokość sekcji ma być wyznaczona przez jej zawartość + padding.

2020-12-28 23:27 UTC, thesvst commented on assets/scss/sections/_ice-creams-and-drinks.scss
> +                height:46%;
Niech te boxy mają sztywną wysokość 200px

2020-12-28 23:27 UTC, thesvst commented on assets/scss/sections/_ice-creams-and-drinks.scss
> +                width:29.33%;
Niech te boxy mają sztywną szerokość 175px

2020-12-28 23:27 UTC, thesvst commented on assets/scss/sections/_ice-creams-and-drinks.scss
> +            width:50%;
Dopasuj szerokość do szerokości zawartości, biorąc pod uwagę marginesy i tak dalej

2020-12-28 23:27 UTC, thesvst commented on assets/scss/sections/_ice-creams-and-drinks.scss
> +                margin:2%;
Ustawić wartości w px. Pamiętać o ustawianiu marginesu za pomocą pseudoklasy nth-child dla poszczególnych elementów, wedle ich potrzeb

2020-12-29 22:10 UTC, mateogaudi commented on assets/scss/sections/_ice-creams-and-drinks.scss
> +                margin:2%;
Poprawione

2020-12-29 22:10 UTC, mateogaudi commented on assets/scss/sections/_ice-creams-and-drinks.scss
> +            width:50%;
Poprawione

2020-12-29 22:10 UTC, mateogaudi commented on assets/scss/sections/_ice-creams-and-drinks.scss
> +                width:29.33%;
Poprawione

2020-12-29 22:10 UTC, mateogaudi commented on assets/scss/sections/_ice-creams-and-drinks.scss
> +                height:46%;
Poprawione

2020-12-29 22:10 UTC, mateogaudi commented on assets/scss/sections/_ice-creams-and-drinks.scss
> +    height:80vh;
Poprawione

2020-12-29 23:49 UTC, merged